### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by 8cH9azbsFifZ** [katlol/trackmyairtag#4]
Running with the instructions provided in the README, this is my result:

trackmyairtag-web-1       | ======== Running on http://0.0.0.0:8080 ========
trackmyairtag-web-1       | (Press CTRL+C to quit)
trackmyairtag-postgres-1  | 2023-05-23 17:54:27.127 UTC [69] ERROR:  relation "log_id_timestamp" already exists
trackmyairtag-postgres-1  | 2023-05-23 17:54:27.127 UTC [69] STATEMENT:  
trackmyairtag-postgres-1  | 	                CREATE TABLE IF NOT EXISTS log (
trackmyairtag-postgres-1  | 	                    id TEXT CHECK (id <> ''),
trackmyairtag-postgres-1  | 	                    name TEXT CHECK (name <> ''),
trackmyairtag-postgres-1  | 	                    address TEXT,
trackmyairtag-postgres-1  | 	                    timestamp BIGINT CHECK (timestamp > 0),
trackmyairtag-postgres-1  | 	                    latitude FLOAT CHECK (latitude > -90 AND latitude < 90),
trackmyairtag-postgres-1  | 	                    longitude FLOAT CHECK (longitude > -180 AND longitude < 180),
trackmyairtag-postgres-1  | 	                    altitude FLOAT,
trackmyairtag-postgres-1  | 	                    raw JSONB,
trackmyairtag-postgres-1  | 	                    UNIQUE (id, latitude, longitude, altitude, timestamp)
trackmyairtag-postgres-1  | 	                );
trackmyairtag-postgres-1  | 	                ALTER TABLE log ADD CONSTRAINT log_id_timestamp UNIQUE (id, timestamp);
trackmyairtag-postgres-1  | 	            
trackmyairtag-web-1       | Error handling request
trackmyairtag-web-1       | Traceback (most recent call last):
trackmyairtag-web-1       |   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
trackmyairtag-web-1       |     resp = await request_handler(request)
trackmyairtag-web-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
trackmyairtag-web-1       |   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
trackmyairtag-web-1       |     resp = await handler(request)
trackmyairtag-web-1       |            ^^^^^^^^^^^^^^^^^^^^^^
trackmyairtag-web-1       |   File "/app/app.py", line 39, in api_db_get_latest
trackmyairtag-web-1       |     res = await app["db"].get_latest()
trackmyairtag-web-1       |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
trackmyairtag-web-1       |   File "/app/utils/db.py", line 22, in get_latest
trackmyairtag-web-1       |     await self._connect()
trackmyairtag-web-1       |   File "/app/utils/db.py", line 19, in _connect
trackmyairtag-web-1       |     await self._initdb()
trackmyairtag-web-1       |   File "/app/utils/db.py", line 88, in _initdb
trackmyairtag-web-1       |     await conn.execute(
trackmyairtag-web-1       |   File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 317, in execute
trackmyairtag-web-1       |     return await self._protocol.query(query, timeout)
trackmyairtag-web-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
trackmyairtag-web-1       |   File "asyncpg/protocol/protocol.pyx", line 338, in query
trackmyairtag-web-1       | asyncpg.exceptions.DuplicateTableError: relation "log_id_timestamp" already exists

**Comment by dhimmel** [comment]
The problem is the `ALTER TABLE` command in:

https://github.com/katlol/trackmyairtag/blob/7972649ff874e292da2b617ea3475baa1b225ba0/utils/db.py#L90-L101

As written it's not idempotent.

Looks like one solution is like https://gist.github.com/michelmilezzi/8f30607cdf9389ea35ff7548bb0226fe#file-idempotent_script-sql-L54


ChatGPT also suggesting:


```sql
DO $$
BEGIN
   IF NOT EXISTS (
      SELECT FROM pg_constraint 
      WHERE conname = 'log_id_timestamp'
      AND conrelid = 'log'::regclass
   )
   THEN
      ALTER TABLE log ADD CONSTRAINT log_id_timestamp UNIQUE (id, timestamp);
   END IF;
END
$$;
```

or

```sql
DO $$
BEGIN
   IF NOT EXISTS (
      SELECT 1 FROM pg_constraint 
      INNER JOIN pg_namespace ON pg_namespace.oid = pg_constraint.connamespace 
      WHERE conname = 'log_id_timestamp' 
      AND nspname = 'public' -- replace with your schema name if different
      AND conrelid = 'log'::regclass
   )
   THEN
      ALTER TABLE log ADD CONSTRAINT log_id_timestamp UNIQUE (id, timestamp);
   END IF;
END
$$;
```

Can't test right away which one works. Could also handle outside of SQL.

**Comment by katlol** [comment]
@dhimmel please reopen if this is still an issue

**Comment by katlol** [comment]
@8cH9azbsFifZ please reopen if this is still an issue

**Comment by dhimmel** [comment]
We haven't fixed this yet, so will still be an issue. Note @katlol only you can reopen this issue.

**Comment by katlol** [comment]
My bad!
