### ISSUE TITLE
deployed from scratch - no items listed

### ISSUE THREAD

**Issue by ldanicel** [katlol/trackmyairtag#5]
I've just deployed this on a macbook M1 running the official docker.app
The container logs show no error and present the db and python app started properly.

http://localhost:8080/ displays an empty map
http://localhost:8080/api/local/items returns a json with proper data by the way it looks.
http://localhost:8080/api/db/latest returns an empty json
http://localhost:8080/api/local/devices returns http 500:

`Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app.py", line 29, in api_local_get_devices
    return web.json_response(await app["devices"].get())
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils/find_my.py", line 25, in get
    return self._parse_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils/find_my.py", line 43, in _parse_data
    row.address = i.address.mapItemFullAddress
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'mapItemFullAddress'`

**Comment by katlol** [comment]
Seems like the format might have changed?

Would you be willing to work on a pull request to fix this? I can then review it.
